// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TouristGuideApp.Data;

#nullable disable

namespace PKS_4_sem4.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TouristGuideApp.Models.Attraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("History")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpeningHours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TicketPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Attractions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "Главная площадь Москвы.",
                            History = "Исторически важное место...",
                            Name = "Красная площадь",
                            OpeningHours = "Круглосуточно (кроме мероприятий)",
                            PhotoImageUrl = "https://ak.picdn.net/shutterstock/videos/1087836581/thumb/1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "Один из крупнейших в России и один из самых значительных в мире театров оперы и балета.",
                            History = "Основан в 1776 году...",
                            Name = "Большой театр",
                            OpeningHours = "Согласно афише",
                            PhotoImageUrl = "https://avatars.mds.yandex.net/i?id=db4e63cbe4ea7456176839f9b2247153_l-5443655-images-thumbs&n=13",
                            TicketPrice = 1500m
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Description = "Один из крупнейших и самых значительных художественных и культурно-исторических музеев России и мира.",
                            History = "Основан в 1764 году...",
                            Name = "Эрмитаж",
                            OpeningHours = "11:00 – 18:00 (выходной - понедельник)",
                            PhotoImageUrl = "https://avatars.dzeninfra.ru/get-zen_doc/8080662/pub_63e8dbe7d8076318c17e3005_63e8dbecd8076318c17e3170/scale_1200",
                            TicketPrice = 500m
                        });
                });

            modelBuilder.Entity("TouristGuideApp.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoatOfArmsImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("History")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Population")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoatOfArmsImageUrl = "https://models.rsbis.com/storage/makets/preview/resize_600x600/3d/90/3d904bff520e868051d015d0f19af950.jpeg",
                            History = "Москва — столица Российской Федерации, город федерального значения...",
                            Name = "Москва",
                            PhotoImageUrl = "https://www.m24.ru/b/d/nBkSUhL2hFggnsq2JL6BrNOp2Z318Ji-mifGnuWR9mOBdDebBizCnTY8qdJf6ReJ58vU9meMMok3Ee2nhSR6ISeO9G1N_wjJ=5lZzUN6kbqlY9eReZPSL0w.jpg",
                            Population = 12655050,
                            Region = "Центральный ФО"
                        },
                        new
                        {
                            Id = 2,
                            CoatOfArmsImageUrl = "https://assets.compmechlab.ru/clients/spb.png",
                            History = "Санкт-Петербург — второй по численности населения город России...",
                            Name = "Санкт-Петербург",
                            PhotoImageUrl = "https://sun9-32.userapi.com/s/v1/ig2/AHWNTHWw4_l3RnxAWQSEKXCAiaFeGS5MAMVvaKx_MIHJ4bt84fyXaURw9IVLvHkNAlFw8_kc2LdgHNDUWz_qAp4x.jpg?quality=95&as=32x32,48x48,72x72,108x108,160x160,240x240,360x360,480x480,540x540,640x640,720x720,1080x1080&from=bu&cs=1080x1080",
                            Population = 5384342,
                            Region = "Северо-Западный ФО"
                        });
                });

            modelBuilder.Entity("TouristGuideApp.Models.Attraction", b =>
                {
                    b.HasOne("TouristGuideApp.Models.City", "City")
                        .WithMany("Attractions")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("TouristGuideApp.Models.City", b =>
                {
                    b.Navigation("Attractions");
                });
#pragma warning restore 612, 618
        }
    }
}
